### ISSUE TITLE
Add version variable for Git task

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa-ansible#11]

**Comment by dverdin** [comment]
Hi Racke,
Do you mean: using repository such as this? https://github.com/sympa-community/sympa/tree/6.2.25b.1
If it is the case, I wonder whether it's really useful. I wanted to let users define any repository, even something that's not Github. In that case, I'm not sure the version would really make sense. Because we don't know for sure if the repo URL will contain a version number at all.
What would be, on your opinion, the added value of adding the version number support?
Cheers,
David

**Comment by racke** [comment]
Hello David,

I am referring to version attribute of the Ansible Git module, which can be a tag, a hash etc.

So this could be empty by default. The repository variable stays the same.

**Comment by dverdin** [comment]
Oh, right!
That's an excellent idea actually. I'll add it.
Thanks for the suggestion!

**Comment by dverdin** [comment]
Forgot to mention it; It's done.
